import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("SAM assisted annotation requires vision prompts and emits reviewed polygons", async () => {
  const source = await readFile("model/training/sam-assisted-nail-annotation.py", "utf8");
  assert.match(source, /vision-guided-box-center-positive-corner-negative-prompts-plus-sam2/);
  assert.match(source, /labels\.append\(\(\[1\] \* len\(positive_set\)\) \+ \(\[0\] \* len\(negative_set\)\)\)/);
  assert.match(source, /annotationMethod.*vision-guided-\{args\.engine\}/);
  assert.match(source, /pointPolygonTest/);
  assert.match(source, /sam-reviewed-overlay/);
  assert.match(source, /box-only fallback returned/);
  assert.match(source, /boxOnlyFallbackPromptCount/);
  assert.match(source, /data-exclusions\.json/);
  assert.match(source, /excludedFiles/);
  assert.match(source, /positivePoints count must match boxes count/);
  assert.match(source, /negativePoints count must match boxes count/);
  assert.match(source, /normalized_points_to_pixels/);
  assert.match(source, /promptModes count must match boxes count/);
  assert.match(source, /has invalid promptModes/);
  assert.match(source, /prompt \{prompt_index\} \(\{prompt_mode\}\)/);
  assert.match(source, /prompt \{index\} polygon conversion failed/);
  assert.match(source, /prompt_modes, strict=True/);
  assert.match(source, /occludedIndices must contain 1-based box indices/);
  assert.match(source, /"occluded": index in occluded_indices/);
  assert.match(source, /positive_set/);
  assert.match(source, /center-negative-corners/);
  assert.match(source, /box-center/);
  assert.match(source, /Tight reviewed boxes should normally use box mode/);
  assert.match(source, /item\.get\("sourceGroup", document\.get\("sourceGroup"\)\)/);
  assert.match(source, /sourceGroup must be a non-empty string on the image or prompt document/);
  assert.match(source, /"sourceGroup": source_group/);
  assert.match(source, /vision-guided-unprompted-mask-pool-plus-per-box-fastsam/);
  assert.match(source, /model\.predictor\.prompt\(base_results, bboxes=\[box\]\)/);
  assert.match(source, /zip\([\s\S]*boxes, points, positive_points, labels, prompt_modes, strict=True/);
});
